name: Publish

on:
    push:
        tags: [ v* ]

jobs:
    check:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
            - run: ./gradlew check

    publish:
        needs: check
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
            - id: get_tag_version
              run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"
            - run: ./gradlew assemble
            - run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
              env:
                  ORG_GRADLE_PROJECT_version: ${{ steps.get_tag_version.outputs.VERSION }}
              shell: bash

    release:
        needs: publish
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v2
            - uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
